// SPDX-FileCopyrightText: Copyright 2026 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

package release

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"time"
)

const (
	// glTokenVar is the environment variable read to authenticate calls to
	// the GitLab API. Public projects need no token.
	glTokenVar = "GITLAB_TOKEN"

	// glMaxErrorBody bounds how much of an API error response is read looking
	// for the error message.
	glMaxErrorBody = 4096
)

// GitLabBackend implements the release Backend on top of the GitLab REST API
// (v4). It works against gitlab.com and self-managed instances, authenticating
// with the GITLAB_TOKEN environment variable when it is set.
//
// GitLab reports no digests, sizes or media types for release asset links, so
// the artifacts read through this backend carry their name and download
// location only. The autogenerated source archives are not considered release
// artifacts and are ignored.
type GitLabBackend struct {
	transport http.RoundTripper
}

// NewGitLabBackend creates a new GitLab release backend.
func NewGitLabBackend() *GitLabBackend {
	return &GitLabBackend{}
}

var _ Backend = (*GitLabBackend)(nil)

// glRelease models the release object returned by the GitLab releases API.
type glRelease struct {
	Name       string     `json:"name"`
	TagName    string     `json:"tag_name"`
	ReleasedAt *time.Time `json:"released_at"`
	Commit     *glCommit  `json:"commit"`
	Assets     glAssets   `json:"assets"`
	Links      glLinks    `json:"_links"`
}

// glCommit models the commit a GitLab release points to.
type glCommit struct {
	ID string `json:"id"`
}

// glAssets models the asset block of a GitLab release. The source archives
// GitLab generates on its own are deliberately not mapped.
type glAssets struct {
	Links []glAssetLink `json:"links"`
}

// glAssetLink models one asset link published in a GitLab release.
type glAssetLink struct {
	Name           string `json:"name"`
	URL            string `json:"url"`
	DirectAssetURL string `json:"direct_asset_url"`
}

// glLinks models the _links block of a GitLab release.
type glLinks struct {
	Self string `json:"self"`
}

// glProject models the project fields the backend reads.
type glProject struct {
	License *glLicense `json:"license"`
}

// glLicense models the license block of a GitLab project as detected by the
// licensee library: its key is the lowercased form of the SPDX identifier.
type glLicense struct {
	Key string `json:"key"`
}

// glErrorBody models the error payload of the GitLab API.
type glErrorBody struct {
	Message string `json:"message"`
}

// FetchReleaseMetadata retrieves from the GitLab API the metadata of the
// release the reference points to. The commit the release was cut from comes
// embedded in the release payload, so resolving it needs no extra calls.
func (b *GitLabBackend) FetchReleaseMetadata(ctx context.Context, ref *Reference) (*Metadata, error) {
	release := &glRelease{}
	if err := b.apiGet(ctx, ref.Host, glReleasePath(ref.Repo, ref.Tag), release); err != nil {
		return nil, fmt.Errorf("fetching release data: %w", err)
	}

	project := &glProject{}
	if err := b.apiGet(ctx, ref.Host, "projects/"+url.PathEscape(ref.Repo)+"?license=true", project); err != nil {
		return nil, fmt.Errorf("fetching project data: %w", err)
	}

	name := release.Name
	if name == "" {
		name = release.TagName
	}
	releaseURL := release.Links.Self
	if releaseURL == "" {
		releaseURL = ref.RepoURL() + "/-/releases/" + url.PathEscape(release.TagName)
	}
	commit := ""
	if release.Commit != nil {
		commit = release.Commit.ID
	}
	license := ""
	if project.License != nil {
		license = project.License.Key
	}

	return &Metadata{
		Name:        name,
		Tag:         release.TagName,
		URL:         releaseURL,
		Commit:      commit,
		License:     license,
		RepoURL:     ref.RepoURL(),
		Published:   release.ReleasedAt,
		BackendData: release.Assets.Links,
	}, nil
}

// FetchArtifactData gathers the data of the asset links published in the
// release that md describes. The link list stashed in the metadata by
// FetchReleaseMetadata is reused when present, avoiding a second API call.
func (b *GitLabBackend) FetchArtifactData(ctx context.Context, ref *Reference, md *Metadata) ([]*Artifact, error) {
	links, ok := md.BackendData.([]glAssetLink)
	if !ok {
		// Prefer the tag captured in the metadata so that a reference to the
		// latest release stays pinned to the release already fetched.
		tag := ref.Tag
		if md.Tag != "" {
			tag = md.Tag
		}
		release := &glRelease{}
		if err := b.apiGet(ctx, ref.Host, glReleasePath(ref.Repo, tag), release); err != nil {
			return nil, fmt.Errorf("fetching release data: %w", err)
		}
		links = release.Assets.Links
	}

	artifacts := make([]*Artifact, 0, len(links))
	for _, link := range links {
		downloadURL := link.DirectAssetURL
		if downloadURL == "" {
			downloadURL = link.URL
		}
		artifacts = append(artifacts, &Artifact{
			Name:        link.Name,
			DownloadURL: downloadURL,
		})
	}
	return artifacts, nil
}

// glReleasePath returns the API path of the release cut from tag, or of the
// project's latest release when tag is empty.
func glReleasePath(repo, tag string) string {
	project := url.PathEscape(repo)
	if tag == "" {
		return fmt.Sprintf("projects/%s/releases/permalink/latest", project)
	}
	return fmt.Sprintf("projects/%s/releases/%s", project, url.PathEscape(tag))
}

// apiGet performs a GET request against the v4 API of the GitLab instance at
// host and decodes the JSON response into the value pointed to by into.
func (b *GitLabBackend) apiGet(ctx context.Context, host, path string, into any) error {
	req, err := http.NewRequestWithContext(
		ctx, http.MethodGet, fmt.Sprintf("https://%s/api/v4/%s", host, path), nil,
	)
	if err != nil {
		return fmt.Errorf("building API request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	if token := os.Getenv(glTokenVar); token != "" {
		req.Header.Set("Private-Token", token)
	}

	client := &http.Client{Transport: b.transport}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("querying the gitlab API at %s: %w", path, err)
	}
	defer resp.Body.Close() //nolint:errcheck // read-only body

	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		errBody := &glErrorBody{}
		//nolint:errcheck,gosec // the error body is a best-effort read
		json.NewDecoder(io.LimitReader(resp.Body, glMaxErrorBody)).Decode(errBody)
		if errBody.Message != "" {
			return fmt.Errorf("gitlab API returned %s querying %s: %s", resp.Status, path, errBody.Message)
		}
		return fmt.Errorf("gitlab API returned %s querying %s", resp.Status, path)
	}

	if err := json.NewDecoder(resp.Body).Decode(into); err != nil {
		return fmt.Errorf("decoding gitlab API response from %s: %w", path, err)
	}
	return nil
}
