[tool.poetry]
name = "poetrylegacy"
version = "0.1.0"
description = ""
authors = ["Test <test@example.com>"]

[tool.poetry.dependencies]
python = ">=3.10"
click = "*"

[tool.poetry.group.dev.dependencies]
iniconfig = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
